"""
Django settings for calculator project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import ctypes
import glob

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from calculator.RpcClient import CalculatorRcpClient

BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vqyaomz12m-r(x&4qy&jbgbghv-7hgwwi-rs7$)d2atd)1@vj+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'calculator',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'calculator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'calculator.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# For C++:
MY_LIB = ctypes.CDLL(glob.glob('/calculator/cpp/build/*/mysum*.so')[0])
# Add:
MY_LIB.add.restype = ctypes.POINTER(ctypes.c_float)
MY_LIB.add.argtypes = [ctypes.c_float, ctypes.c_float]
# Subtract:
MY_LIB.sub.restype = ctypes.POINTER(ctypes.c_float)
MY_LIB.sub.argtypes = [ctypes.c_float, ctypes.c_float]
# Multiply:
MY_LIB.mult.restype = ctypes.POINTER(ctypes.c_float)
MY_LIB.mult.argtypes = [ctypes.c_float, ctypes.c_float]
# Divide:
MY_LIB.divide.restype = ctypes.POINTER(ctypes.c_float)
MY_LIB.divide.argtypes = [ctypes.c_float, ctypes.c_float]
# Exponentiate:
MY_LIB.power.restype = ctypes.POINTER(ctypes.c_float)
MY_LIB.power.argtypes = [ctypes.c_float, ctypes.c_float]

# For Java:
CALCULATOR_RPC = CalculatorRcpClient('calculator-rabbitmq', 'rpc_queue')
# CALCULATOR_RPC = CalculatorRcpClient('localhost', 'rpc_queue')
